spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.237.101:8848

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"