spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.237.101:8848

    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.237.102:8858
        client-ip: 192.168.43.81
server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true
