spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      bindings:
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        output: {destination: test-topic, content-type: application/json}
      rocketmq:
        binder:
          # RocketMQ 服务器地址
          namesrv-addr: 192.168.237.104:9876


server:
  port: 9099

management:
  endpoints:
    web:
      exposure:
        include: '*'