spring:
  application:
    name: nacos-provider

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.58:8848

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"